---
language: ruby
sudo: false
cache: bundler

rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.1
  - ruby-head

env:
  - DB=sqlite     RAILS='~> 5.0'
  - DB=postgresql RAILS='~> 5.0'
  - DB=mysql      RAILS='~> 5.0'
  - DB=sqlite     RAILS='~> 4.2'
  - DB=postgresql RAILS='~> 4.2'
  - DB=mysql      RAILS='~> 4.2'

matrix:
  allow_failures:
    - rvm: ruby-head

before_script:
  # - mysql -e 'create database myapp_test'
  # - psql -c 'create database myapp_test' -U postgres
  - bundle exec rake dummy:setup
  - bundle exec rake app:db:create
  - bundle exec rake app:db:migrate
  - bundle exec rake app:db:migrate RAILS_ENV=test

script:
  - bundle exec rake test
